#!/bin/sh
COMMIT_MSG_FILE=$1
REGEXP="^DJ\-(100000|[1-9][0-9]{0,4}|0)"
# Check if the commit message is empty
if [ ! -s "$COMMIT_MSG_FILE" ];
  then
    echo "Error: Commit message is empty. Please provide a commit message." >&2
    exit 1
  else
  COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
  if [[ $COMMIT_MSG =~ $REGEXP ]]; 
  #if [[ $COMMIT_MSG =~ ^DJ\-(100000|[1-9][0-9]{0,4}|0) ]]; 
    then
      echo "Commit: $COMMIT_MSG";
      exit 0;
    else
      echo "Error:\nCommit message must start from 'DJ-'+'task nubmer'\n";
      echo "Regexp is: $REGEXP";
      echo "is wrong commit message: $COMMIT_MSG";
      exit 1;
  fi
fi

exit 0
