volumes:
  jenkins_configuration:
  jenkins-agent-data:
  
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets/id_jenkins:/run/secrets/SSH_AGENT_KEY:ro
      - ./casc.d:/var/jenkins_home/casc.d/:ro
    environment:
      - JENKINS_EXT_URL=http://localhost:8080
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.d/
      - org.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
      - GITHUB_APP_ID
      - GITHUB_APP_KEY
      - PUBLIC_IP
      - STF_API_TOKEN
      - STF_HOST_NAME
      # - JENKINS_OPTS=-Djenkins.install.runSetupWizard=false
  jenkins-agent:
    # platform: linux/amd64
    build: ./agent
    restart: unless-stopped
    privileged: true
    volumes:
        - jenkins-agent-data:/home/jenkins:rw
        - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
        - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDw1e+7gHiF3f3gn/hpFOhlSWiShG9LbV6xLADwDvzDw root@debian-parallel
