---
- include_tasks: install-on-rhel.yamlyml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-on-debian.yaml
  when: ansible_os_family == 'Debian'

- include_tasks: app-install.yaml
  tags: db_host_ip
