apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: study-hw13
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value of 'root-pass'
  MYSQL_DATABASE: Zmxhc2tfYWxi       # base64 encoded value of 'flask_alb'
  MYSQL_USER: YWRtaW4=               # base64 encoded value of 'admin'
  MYSQL_PASSWORD: cGFzcw==           # base64 encoded value of 'pass'